### ISSUE TITLE
CLX40E GETS32 RUM task

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls-issues#14]
From the [Elog](https://www-bd.fnal.gov/Elog/?orEntryId=248138):

> Ops received a call from Clay Leonard who was having trouble getting some readbacks from devices on CLX40E with the ACNET error "not connected as a RUM task". Ops contacted Keith Engell who said that it looked like the same problem that they encountered yesterday and to call Jim Smedinghoff. Jim had ops restart the FE acnet process from within the node. This resolved the issue. It was GETS32 that was missing the RUM connection. Clay confirmed that his readbacks were back, and Jim will look further into this issue.

EDIT: Use the quote instead of code formatting. - beau

**Comment by awattsFNAL** [comment]
From Dan Lambert this morning, problem persists:
`It looks like that node went down again, or another issue, a little after 3:30 this morning. All my devices are displaying 1-28 errors, not just when I try to issue a command. See this ACNET page: P126 Vacuum <17>`

**Comment by awattsFNAL** [comment]
It seems this could be related to Issue #16. A takeaway is that the D31 reboot feature doesn't seem to actually restart the Erlang process on virtual front-ends. Operators have been implicitly assuming that it would, so their "reboots" may be ineffective.

**Comment by kengell** [comment]
I believe most Ops (the ones I've talked to) know that one has to log into the CLX node and run

`$ acnet restart run_erl_fe`

**Comment by awattsFNAL** [comment]
Should I close this issue now, in favor of the broader issue of Erlang memory leaks?

**Comment by awattsFNAL** [comment]
Closing this issue, tracking via the broader issue #16
