### ISSUE TITLE
IRMs not synching DB updates

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls-issues#3]
Mechanism for IRMs to sync new changes to the device database stopped functioning; noticed late 9/20, but may be a persistent issue not noticed during the shutdown.

**Comment by awattsFNAL** [comment]
Mechanism for IRMs to sync new changes to the device database stopped functioning; noticed late 9/20, but may be a persistent issue not noticed during the shutdown. Could be related to Alma Linux 9 switch for the synchronization service.

**Comment by finstrom** [comment]
It appears this broke some time after 7:24pm 9/8/23 and was definitely broken by 10:14am 9/11/23. Errors can be seen in downld logs. Look at /usr/local/userb/dabbel/downld_logs/*. There are also errors in centra:/var/log/messages:

Sep 21 15:13:34 centra systemd[1]: downld.service: Main process exited, code=exited, status=134/n/a
Sep 21 15:13:34 centra systemd[1]: downld.service: Failed with result 'exit-code'.
Sep 21 15:13:34 centra systemd[1]: downld.service: Consumed 2min 22.198s CPU time.
Sep 21 15:16:16 centra systemd[1]: Started downld for IRM's.

**Comment by finstrom** [comment]
This seems to be part of the problem - note the year - (output from downld_logs):
Begin scan of db_audit table at 18-JUL-2002 16:54:15

From downld.cpp:
/*
  Get the date/time to start audit table scan
*/
clinks = fe_tbl[cfe].clinks;
clinks_to_date( clinks, buffer1);
buffer1[20] = '\0';
fprintf( fp,"Begin scan of db_audit table at %s\n", buffer1);

**Comment by finstrom** [comment]
The bad timestamps per IRM (for example 18-Jul_2002) are stored in the database table johnson.downld_data. The bad timestamps were updated to the last time that downld successfully ran (found in the log files) and downld is working again.

**Comment by awattsFNAL** [comment]
Re-opening this issue: Mike Kucera reports that IRM database downloads are broken again.

**Comment by awattsFNAL** [comment]
From Jim:
>The problem might (or might not) be related to upgrading to Alma Linux.  I am reading the downld code to try and understand how it is supposed to work.  Centra is still using SLF7 compiled code.  It would at least be less confusing if we could restart the centra services to use the Alma 9 compiled versions.

I'm wondering if it's best we wait for Denise to get back from ICALEPCS before restarting CENTRA.
