### ISSUE TITLE
"Control's API" Not Found

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/controls-issues#35]
### Describe the bug

This page, <https://www-bd.fnal.gov/javadoc/builds/current/index.html>, is not found.

@kjhazelwood says it was working a couple of weeks ago.

The link from, <https://www-bd.fnal.gov/controls/java/>, is highlighted with a blue box in this picture.
![Controls Java page with Control's API highlighted](https://github.com/fermi-ad/controls/assets/3767966/f4f3e023-f47a-4044-9fbd-caa07f3b71ba)

### To Reproduce

1. Go to <https://www-bd.fnal.gov/controls/java/>
2. Click on "Control's API"
3. See "Page Not Found" error

### Affected system

- [X] Java
- [X] Web

**Comment by tezdog** [comment]
https://www-bd.fnal.gov/javadoc/builds/current/log
/var/www/html/javadoc/buildtools/govdoc: line 28: /usr/java/default/bin/javadoc: No such file or directory
(this is on daesrv)

**Comment by tezdog** [comment]
Please take a look, I think this is resolved, minus me committing the fix to CVS make it permanent which I will do before closing this issue.  Thanks.

**Comment by beauremus** [comment]
This is working! Thanks
