### ISSUE TITLE
AD GPS NTP firmware update

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls-issues#41]
Firmare updates for the AD GPS NTP appliances

**Comment by awattsFNAL** [comment]
Background from Tim:

> In discussing our NTP server setup with Chandler, he asked when the
appliances were last updated.  We investigated and found that there is a
manufacturer recommended update from 2021 which updates
openssl/openssh/ntp/apache/php that we have not applied.

> We'd like to coordinate getting these updates installed during the grey
period.

> Normally I think we have updated the appliance that does not provide the 1
pulse per second signal to the clock system first, then moved the PPS wire
over and updated the other appliance.  This could still likely result in
at least one missed pulse, so we should coordinate that with a clock
person.

**Comment by awattsFNAL** [comment]
Context from Tim:

> We have 2 NTP servers.  We would update the one not sending the 1 pulse
per second signal to the clock system first.  Then once it is up and
time sync'd we would move the wire for the PPS signal over to it.  At that
point if the clock system remains happy, we would update the other system,
if the clock system is not happy, we could move the wire back to the old
one.  The expected impact is a loss of 1-2 PPS signals, the potential
impact is a longer loss until we realize there is an issue and move the
cable back.  So we would want someone to be available to confirm the clock
system is happy after the cable swap.

> I think the impact could be to the hardware clock as well, this is not
particularly related to multicast clock, it is the on-the-second pulse
signal to the clock system that is interrupted.  I'm not sure how the
clock system uses that... it may not even care about the interruption, if
it only uses the pulse to avoid drift.

**Comment by awattsFNAL** [comment]
Planning for 1100 on Wednesday 11/29/23 if there are no stakeholder objections at the AD/Ops Wednesday 0900 meeting.

**Comment by awattsFNAL** [comment]
Context from Mark regarding potential impact:
> The TCLK $8F is generated from the 1PPS signal coming from the NTP Server.  This EVENT would go away but the rest of the clock and EVENTs would continue to be played out.  I can’t say what downstream equipment that watches for the $8F will do.

**Comment by tezdog** [comment]
This work is done and Chris Olsen confirmed that things look fine from their side.  Thanks!
