### ISSUE TITLE
DSE10 outage

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls-issues#42]
DSE10 hardware failure took down RabbitMQ OAC BUNNY1.

**Comment by awattsFNAL** [comment]
No degradation of service, just loss of redundancy.

**Comment by finstrom** [comment]
@lgmillsx recovered the node. No clues as to what the problem was.

**Comment by awattsFNAL** [comment]
Reopening due to another failure over the weekend.
[https://www-bd.fnal.gov/Elog/?orEntryId=250275](https://www-bd.fnal.gov/Elog/?orEntryId=250275)

**Comment by lgmillsx** [comment]
Again, another lock-up with no traces - the third this year for this host.  Re-seated all memory and internal MB connectors.  If it happens again, will probably replace power supply.
