### ISSUE TITLE
LOOKUP service failure

### ISSUE THREAD

**Issue by awattsFNAL** [fermi-ad/controls-issues#45]
First [noted by Ops](https://www-bd.fnal.gov/Elog/?orEntryId=250627), there was a failure of the lookupd service. Root cause is unclear, but restarting clxsrv addressed the issue for now.

**Comment by rneswold** [comment]
@charlieking65 found that only 1, of the normally 3, services were running. And the one that was running was reporting out of memory errors. He (and/or Denise?) restarted all of them.

**Comment by awattsFNAL** [comment]
Closing this issue, as it hasn't returned since the restart.
