### ISSUE TITLE
MI/RR IP readback/plotting issues

### ISSUE THREAD

**Issue by beauremus** [fermi-ad/controls-issues#54]
### Describe the bug

See the issue reported in the ELog, https://www-bd.fnal.gov/Elog/?orEntryId=254065.

Recycle Ion Pump plots are showing strange behavior and producing errors when the data requested is a higher rate than 1HZ.

![strange_plot](https://github.com/fermi-ad/controls/assets/3767966/09937693-a15b-4c44-a05d-4228cdc919e5)
![plot_errors](https://github.com/fermi-ad/controls/assets/3767966/31f1a193-898a-4cc2-9339-c10edd207731)
![error_definition](https://github.com/fermi-ad/controls/assets/3767966/94428d2a-73a8-41a7-ac24-e3135a9c7cb6)

### To Reproduce

1. Go to FTP
2. Plot R:IP3170 at a rate higher than 1Hz
3. Observe "strange" data

### Affected system

- [X] Console
- [ ] Java
- [ ] Web
- [ ] Synoptic
- [X] Front End
- [ ] Central Service

**Comment by kengell** [comment]
I was told that this an old and known issue w/ Erlang FEs.  FTP higher than 1Hz results in undesirable behavior.  I'll run some tests on the FE in question and see what pops out in the logs.  The workaround is to always plot at 1Hz.

**Comment by kengell** [comment]
For the device in question (R:IP3170) this is handled via the CLX56 FE via a modbus link to a Raspberry Pi based device. 

The FE config is:

>             ,{49, modbus_driver, {"cia-mi30203", %% MI30_
>                              [   
>                          %% Digital reads (slots 0-15)
>                           {0,1,3,16#0100,112}  %% slots 0-6 
>                          ,{1,1,3,16#0170,112}  %% slots 7-13
>                          %% Analog reads (slots 0-15)
>                          ,{16,1,3,16#0300,112} %% slots 0-6 
>                          ,{17,1,3,16#0370,112} %% slots 7-13
>                          ],  
>                          [   
>                           {sample_rate, 989}
>                          ,{timeouts, {700,700,cast}}
>                          ,{segtyp, bigseg}
>                          ]   
>                          }}  

Not seeing any log entries w/ attempting to plot at 15Hz.

**Comment by kengell** [comment]
Email update

> I found an old Elog entry from 2021 where we were able to plot vacuum data from I:IP100E at 15Hz here: https://www-bd.fnal.gov/Elog/?orEntryId=197077  From D80 that pump was moved to PiVac and CLX56E back in 2018.
>

**Comment by kengell** [comment]
Going through acsys-fe code looking for modifications to ftpman.erl and ftpman_protocol.erl since 2021.

> $ git log ftpman_protocol.erl
> commit e35d6d3d93c306939a9bc132cc9b0fb38a4bcbf6
> Author: 
> Date:   Mon Apr 17 14:29:11 2023 -0500
> 
>     Put in commented out diagnostic for Type Code 8
> 
> commit b6ec39b7c5d51669919003448fd0d19f85f9d6e2
> Author: 
> Date:   Wed Dec 7 11:13:06 2022 -0600
> 
>     For reply to a retrieve snapshot data request, remove HasTS field that is
>     unexpected by receiver (SA1003).
>

**Comment by kengell** [comment]
For completeness on the followup, and in response to the email stating that in 2021 we could plot ion pumps at 15Hz.

During the long shutdown we have:

- Upgraded the CLX nodes from Scientific Linux to Alma Linux Aug-2023
- Upgraded Erlang from v21 to v26.1 in October-2023
- Made chages to the Modbus driver code.

I'm am currently consulting w/ Rich and Dennis to effect a solution which we hope to have today.

**Comment by mguzman04** [comment]
It seems that there was a similar issue back in [July](https://www-bd.fnal.gov/Elog/?orEntryId=245135). If some of the changes happened after July, maybe they can be dismissed?

**Comment by kengell** [comment]
Bug fixed.  CLX56E was updated w/ new Erlang libraries and the FE was restarted.  15Hz support now works.

**Comment by beauremus** [comment]
![Screenshot 2024-02-26 at 09 40 11](https://github.com/fermi-ad/controls/assets/3767966/75f762db-a13a-4bb5-b8e0-8b14f35ea21c)
This appears to be working 🚀
