### ISSUE TITLE
[14 -7] status when requesting FTP data using acsys-py

### ISSUE THREAD

**Issue by kjhazelwood** [fermi-ad/controls-issues#66]
### Describe the bug

This request `I:BEAM@P,720H,TRUE` returns status [14 -7], complaining of no scaling information for the requested property (reading). Request `I:BEAM@P,1H,TRUE` returns data. Im guessing there is an issue with FTP data and scaling readings? Happens on different devices from different FEs and rates > 15Hz. Tried specifying multiple DPMs, all returned the same.

### To Reproduce

`I:BEAM@P,720H,TRUE`

### Affected system

- [ ] Console
- [ ] Java
- [ ] Web
- [ ] Synoptic
- [ ] Front End
- [X] Central Service

**Comment by kjhazelwood** [comment]
I should add that the same code and requests worked ~6-9 months ago

**Comment by beauremus** [comment]
We can see this problem and are looking into a solution.

**Comment by rainswor** [comment]
It's better, `'I:BEAM@P,720H,TRUE'` returns data but other devices do not. For example `'I:QERR@P,720H,TRUE'` gives `WARNING:__main__:I:QERR@P,720H,TRUE: [1 -44]`.

I get similar errors for I:BEAM if i ask for 360 Hz, `WARNING:__main__:I:BEAM@P,360H,TRUE: [1 -44]`

**Comment by beauremus** [comment]
I believe this is fixed. Please let us know if you still have issues.
